apiVersion: v1
kind: ConfigMap
metadata:
  name: service-users
data:
  lb_auth_issuer_uri: http://172.20.86.138:30923
  lb_user_uri: http://172.20.86.138:30146
  port: "8001"
  db_host: "db-mysql:3306"
  db_database: "db_docker_users"
  db_username: "root"
  db_password: ""
  service_courses_url: "service-courses:8002"
  mi_env: "prod"
  application.yaml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente DESARROLLO
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente PRODUCCION
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-courses-xd
data:
  port: "8002"
  db_host: "db-postgres:5432"
  db_database: "db_docker_courses"
  db_username: "postgres"
  db_password: "saksa"
  service_users_url: "service-users:8001"
