apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-courses
  template:
    metadata:
      labels:
        app: service-courses
    spec:
      containers:
      - image: cvaldiviape/mek-service-courses:v6
        name: mek-service-courses
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: db_database
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: db_password
          - name: SERVICE_USERS_URL
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: service_users_url