apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      melek: db-postgres
  template:
    metadata:
      labels: 
        melek: db-postgres
    spec:
      containers:
      - image: postgres:15
        name: db-postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: "saksa"
          - name: POSTGRES_DB
            value: "db_docker_courses"
        volumeMounts:
          - name: mi-volumen-postgresql
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: mi-volumen-postgresql
        hostPath:
          path: /var/lib/postgresql/data
          type: DirectoryOrCreate