apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-courses
  template:
    metadata:
      labels:
        app: service-courses
    spec:
      containers:
      - image: cvaldiviape/mek-service-courses:latest
        name: mek-service-courses
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            value: "8002"
          - name: DB_HOST
            value: "db-postgres:5432"
          - name: DB_DATABASE
            value: "db_docker_courses"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            value: "saksa"
          - name: SERVICE_USERS_URL
            value: "service-users:8001"