apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      melek: db-postgres
  template:
    metadata:
      labels: 
        melek: db-postgres
    spec:
      containers:
      - image: postgres:15
        name: db-postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: db_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: service-courses-xd
                key: db_database
        volumeMounts:
          - name: mi-volumen-postgresql
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: mi-volumen-postgresql
        persistentVolumeClaim:
          claimName: postgres-pvc